### PR TITLE
Fixed Exclamation Visibility and Door Interaction Fix

### LINKED ISSUE #14: Exclamation point remains in Catacombs doorway even after opening the door
The door is closed when the player first approaches (even after retrieving the key, etc.) and the exclamation appears to open the doors. Once they are open, when the player passes through the open doorway in either direction, the exclamation point appears again, with no interactivity.

Screen Shot 2022-09-26 at 4 21 23 PM

### PR DESCRIPTION
**Pull request by MarvelProgramming**
-Made it so the door has it's "interactable" property set to "false" upon opening to prevent the exclamation point from showing up and the door being set to the player's "inRangeObject" 
-Made it so the door has it's "spellable" property set to "false" upon opening to prevent the player from attempting to open the door and having an animation play as though they were unlocking it

For issue #14

### CODE REVIEW

**Comment by MarvelProgramming** [comment]
In commit [ffc8ba6](https://github.com/TwilioQuest/twilioquest-api-academy/pull/15/commits/ffc8ba6648effce01e0fc5f82b3bd7d660220876), I explicitly set the player's `inRangeObject` to null. This effectively hides the exclamation point, since the door's `interactable` flag is changed to `false` after opening. I wonder if it would make more sense to do something like this all the time, though. In other words, "resetting" the player's `inRangeObject` whenever they interact with something, to ensure that thing can still be acted upon following the interaction

File: levels/inside_perimeter/events.js [hunk 1]
```diff
@@ -263,6 +270,8 @@ module.exports = async function (event, world) {
     }
 
     openDoor("scroll_room_door");
+    // Forces the player's exclamation point to become hidden after opening the door
+    event.target.level.player.inRangeObject = null;
```
Comment (rmkubik) [inline levels/inside_perimeter/events.js:274]: Oh wow, this is wild. We don't have any sensible functionality to make an object _stop_ being in range of the player do we?

**Comment by rmkubik** [comment]
> In commit [ffc8ba6](https://github.com/TwilioQuest/twilioquest-api-academy/pull/15/commits/ffc8ba6648effce01e0fc5f82b3bd7d660220876), I explicitly set the player's `inRangeObject` to null. This effectively hides the exclamation point, since the door's `interactable` flag is changed to `false` after opening. I wonder if it would make more sense to do something like this all the time, though. In other words, "resetting" the player's `inRangeObject` whenever they interact with something, to ensure that thing can still be acted upon following the interaction

I think something like this makes a lot of sense. Can you draft this up as an issue clearly explaining this idea to make sure we're on the same page for how we'd implement this?

I wonder if we'd want some other functionality too though. Just clearing the Operator's inRangeObject after interaction doesn't work if we vanish an object in front of their face when they enter a TriggerArea for example.

I wonder if we should create functions on SpriteObject for "disableInteraction" and "enableInteraction". When the `disableInteraction` function is called it could clear out the player's current inRangeObject if it matches itself.

```js
disableInteraction() {
  if (this.level.player.inRangeObject === this) {
    this.level.player.inRangeObject = null;
  }
}
```

Either way, this discussion should probably be happening on the new issue, not this PR!

**Review by rmkubik — APPROVED** [review]
Tested it quickly, and looks good!

**Comment by MarvelProgramming** [comment]
> Can you draft this up as an issue clearly explaining this idea to make sure we're on the same page for how we'd implement this?

Will do! I'll create an issue on the TwilioQuest repo and link back to this for reference

File: levels/inside_perimeter/events.js (hunk 1 above)
Comment (MarvelProgramming) [reply levels/inside_perimeter/events.js:274]: Not yet, at least 😎
